version = 1
SPDX-PackageName = "Gardenlinux builder"
SPDX-PackageSupplier = "SAP SE <gardenlinux@gardenlinux.io>"
SPDX-PackageDownloadLocation = "https://github.com/gardenlinux/builder"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and Gardenlinux contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and Gardenlinux contributors"
SPDX-License-Identifier = "CC-BY-4.0"